# Generated by Django 5.0.6 on 2026-01-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_parameter',
        ),
    ]
