# Generated by Django 5.0.6 on 2026-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_fact_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='date_visited',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='status',
            field=models.CharField(choices=[('visited', 'Visited'), ('current', 'Current'), ('not_visited', 'Not Visited')], default='not_visited', max_length=255),
        ),
    ]
