# Generated by Django 5.0.6 on 2026-01-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_fact_date_visited_fact_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
