# Generated by Django 5.0.6 on 2026-01-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='facts', to='facts.category'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
