# Generated by Django 5.0.6 on 2026-08-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0005_alter_fact_categories_alter_fact_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('thumbs_up', 'Thumbs up'), ('funny', 'Funny'), ('mind_blown', 'Mind blown'), ('weird', 'Weird'), ('love', 'Love')], max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='facts.fact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fact_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(check=models.Q(('session_id__isnull', True), ('user', None), _connector='XOR'), name='session_id_or_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('fact', 'reaction', 'user'), name='unique_fact_reaction_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('fact', 'reaction', 'session_id'), name='unique_fact_reaction_session_id'),
        ),
    ]
